Repository VizerISD/personalhealthcarewallet, pull requests merged in 2023-04, with the labels that each got.

#34 Finished replacing all wallet addresses with names.
  src/components/@shared/Publisher/index.tsx
  src/components/Asset/AssetContent/EditHistory.tsx
  src/components/Asset/AssetContent/MetaFull.tsx
Labels: enhancement

#37 Added link for names on asset page
  src/components/Asset/AssetActions/Compute/assetAccess.module.css
  src/components/Asset/AssetActions/Compute/assetAccess.tsx
Labels: enhancement

#39 Changed sample file to schema
  content/publish/form.json
Labels: enhancement

#41 Reworked icons on tx history and swapped timelines
  src/@images/checkmark.svg
  src/components/Asset/AssetContent/TransactionHistoryVisualization.tsx
  src/components/Asset/AssetContent/index.tsx
Labels: enhancement

#43 36 add asset download
  src/components/Asset/AssetActions/index.tsx
Labels: enhancement

#48 resize button to full length & fix text color
  src/components/Asset/AssetActions/Compute/assetAccess.module.css
Labels: enhancement

#47 Reworked the profile tabs
  src/components/Asset/AssetActions/Compute/index copy.tsx
  src/components/Profile/Header/Stats.tsx
  src/components/Profile/History/Downloads.tsx
  src/components/Profile/History/PublishedList.tsx
  src/components/Profile/History/index.tsx
Labels: enhancement

#55 Added asset link on profile page
  content/static_data/mocked-medical-records.json
  src/components/Profile/History/MedicalRecordsTab.tsx
Labels: enhancement

#57 Added tooltips with directions to visualizations
  src/components/Asset/AssetContent/index.module.css
  src/components/Asset/AssetContent/index.tsx
Labels: enhancement

#58 Cleaned up txhistoryviz file and fixed date-time
  src/components/Asset/AssetContent/TransactionHistoryVisualization.tsx
Labels: enhancement

#61 Updated the mocked data for the older bloodwork record.
  content/static_data/mocked-bloodwork2/access-events.json
  src/components/Asset/AssetContent/IndividualUseVisualization.tsx
Labels: enhancement

#65 53 mockedcovidtest
  content/static_data/mocked-covidtest/access-events.json
  content/static_data/mocked-medical-records.json
  src/components/Asset/AssetContent/IndividualUseVisualization.tsx
  src/components/Asset/AssetContent/TransactionHistoryVisualization.tsx
  src/components/Profile/Header/Stats.tsx
Labels: enhancement

#66 Updated data and asset page for older bloodwork asset
  content/static_data/mocked-medical-records.json
  src/components/@shared/AssetType/index.tsx
  src/components/@shared/Publisher/index.tsx
  src/components/Asset/AssetContent/MetaMain/MetaAsset.tsx
  src/components/Asset/AssetContent/MetaMain/MetaInfo.tsx
  src/components/Asset/AssetContent/index.tsx
  src/components/Asset/index.tsx
Labels: enhancement

#71 Fully mocked Asset Page for 2nd Bloodwork Asset
  content/static_data/mocked-bloodwork1/access-events.json
  content/static_data/mocked-medical-records.json
  src/components/@shared/AssetType/index.tsx
  src/components/@shared/Publisher/index.tsx
  src/components/Asset/AssetActions/Download.tsx
  src/components/Asset/AssetContent/IndividualUseVisualization.tsx
  src/components/Asset/AssetContent/MetaMain/MetaAsset.tsx
  src/components/Asset/AssetContent/MetaMain/MetaInfo.tsx
  src/components/Asset/AssetContent/TransactionHistoryVisualization.tsx
  src/components/Asset/AssetContent/index.tsx
  src/components/Asset/index.tsx
Labels: enhancement

#72 53 mockedcovidtest
  content/static_data/mocked-insuranceform/access-events.json
  content/static_data/mocked-medical-records.json
  package-lock.json
  src/components/Asset/AssetContent/IndividualUseVisualization.tsx
  src/components/Asset/AssetContent/TransactionHistoryVisualization.tsx
  src/components/Profile/Header/Stats.tsx
Labels: enhancement

#74 Fixed styling/colors
  src/components/Asset/AssetActions/Compute/assetAccess.tsx
  src/components/Asset/AssetContent/IndividualUseVisualization.tsx
  src/components/Asset/AssetContent/TransactionHistoryVisualization.tsx
Labels: enhancement, Usability Test Suggestion

#75 53 mockedcovidtest
  content/static_data/mocked-medical-records.json
  src/components/Asset/AssetActions/Compute/assetAccess.tsx
Labels: enhancement

#73 64 safety check asset access
  src/components/Asset/AssetActions/Compute/assetAccess.module.css
  src/components/Asset/AssetActions/Compute/assetAccess.tsx
Labels: enhancement

#76 Removed the free Header. #68
  src/components/@shared/Price/PriceUnit.tsx
Labels: enhancement

#78 Changed asset access to just access #77
  src/components/Asset/AssetActions/index.tsx
Labels: Usability Test Suggestion
